module Yaml
  module Converter
    class MarkdownEmitter
      START_YAML: String
      END_YAML: String
      VALIDATED_STR: String
      NOTE_STR: String

      def initialize: (Yaml::Converter::options options) -> void
      def set_validation_status: (Symbol) -> void
      def emit: (Array[String]) -> Array[String]
    end
  end
end
